name: Build .deb

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag para publicar"
        required: true
        type: string

permissions:
  contents: write

jobs:
  build-deb:
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || github.event.inputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install build tooling
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential debhelper devscripts fakeroot

      - name: Symlink debian directory
        run: |
          if [ ! -e debian ]; then
            ln -s host-agent/debian debian
          fi
          ls -l debian

      - name: Build package
        run: |
          dpkg-buildpackage -us -uc
          mkdir -p artifacts
          find .. -maxdepth 1 -type f \( -name '*.deb' -o -name '*.dsc' -o -name '*.changes' -o -name '*.buildinfo' -o -name '*.tar.*' \) -exec mv {} artifacts/ \;
          ls -l artifacts

      - name: Upload .deb artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debs
          path: artifacts/*.deb

      - name: Attach to GitHub Release
        if: env.RELEASE_TAG != ''
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          files: artifacts/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
